version: '3.6'

services:
  mysql8:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql8
    hostname: mysql8
    restart: always
    volumes:
      - ./DB/MySQL:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '3000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 3x4mpl3
  php7apache:
    build: dockerfiles/php7/.
    container_name: php7apache
    hostname: php7apache
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./dockerfiles/php7/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - '80:80'
    links:
      - mysql8

networks:
  default:
    name: www-mysql
#DB/MySQL